-- stg_events: staging layer for match events
-- No transformations applied; columns are passed through as-is from raw_events.
-- Grain: one row per unique event (event_id) within a match (match_id).

select
    event_id,
    match_id,
    event_index,
    event_type_id,
    event_type_name,
    period,
    minute,
    second,
    timestamp,
    team_id,
    team_name,
    player_id,
    player_name,
    position_id,
    position_name,
    location_x,
    location_y,
    possession_team_id,
    possession_team_name,
    play_pattern_id,
    play_pattern_name,
    duration,
    possession,
    under_pressure,
    off_camera,
    out,
    counterpress,
    pass,
    shot,
    carry,
    dribble,
    duel,
    clearance,
    block,
    interception,
    goalkeeper,
    foul_committed,
    foul_won,
    bad_behaviour,
    ball_receipt,
    ball_recovery,
    miscontrol,
    substitution,
    tactics

from {{ ref('raw_events') }}
